import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Styles from '../styles/Home.module.scss';
import Card from '../components/atoms/Card';
import LoginForm from '../components/molecules/LoginForm';
import Tab from '../components/molecules/Tab';
import RegisterForm from '../components/molecules/RegisterForm';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Styles['main']}>
        <Card>
          <Tab>
            <Tab.Panel title="Giriş Yap">
              <LoginForm />
            </Tab.Panel>
            <Tab.Panel title="Üye Ol">
              <RegisterForm />
            </Tab.Panel>
          </Tab>
        </Card>
      </main>
    </>
  );
}
